# Generated by Django 6.0.6 on 2026-06-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('client', 'Частное лицо'), ('b2b', 'Компания (B2B)')], default='client', max_length=10, verbose_name='Тип аккаунта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
    ]
