# Generated by Django 6.0.6 on 2026-07-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес отправления')),
                ('to_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('tariff', models.CharField(choices=[('standard', 'Стандарт'), ('express', 'Экспресс'), ('refrigerated', 'Рефрижератор')], default='standard', max_length=20, verbose_name='Тариф')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Расчётная стоимость')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Расстояние (км)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вес (тонн)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Объём (м³)')),
                ('pickup_date', models.DateField(verbose_name='Дата забора')),
                ('cargo_description', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('pending_review', 'На рассмотрении'), ('processed', 'В обработке'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для доставки')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('logo', models.ImageField(upload_to='clients/logos/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('license_number', models.CharField(blank=True, max_length=30, verbose_name='Номер ВУ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (тонн)')),
                ('date', models.DateField(verbose_name='Дата выполнения')),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='portfolio/')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена от')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='services/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Трекинг-номер')),
                ('from_address', models.TextField(blank=True, verbose_name='Адрес забора')),
                ('to_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вес (тонн)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Объём (м³)')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('pickup_date', models.DateField(verbose_name='Дата забора')),
                ('delivery_date_expected', models.DateField(blank=True, null=True, verbose_name='Плановая доставка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('in_progress', 'В пути'), ('delivered', 'Доставлена'), ('canceled', 'Отменена'), ('problem', 'Проблема')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('in_progress', 'В пути'), ('delivered', 'Доставлена'), ('canceled', 'Отменена'), ('problem', 'Проблема')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Guter Transport', max_length=200, verbose_name='Название компании')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Слоган')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Режим работы')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('telegram', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Клиент')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='Госномер')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Грузовик'), ('van', 'Фургон'), ('refrigerator', 'Рефрижератор'), ('trailer', 'Прицеп')], default='truck', max_length=20, verbose_name='Тип')),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Грузоподъёмность (т)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Объём кузова (м³)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['license_plate'],
            },
        ),
    ]
