# Generated by Django 6.0.6 on 2026-07-03 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargorequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cargo_requests', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_departures', to='transport.city', verbose_name='Город отправления'),
        ),
        migrations.AddField(
            model_name='cargorequest',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_arrivals', to='transport.city', verbose_name='Город назначения'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.client'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_departures', to='transport.city', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_arrivals', to='transport.city', verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transport.portfolioproject'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='transport.servicecategory'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_shipment', to='transport.cargorequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='transport.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_departures', to='transport.city', verbose_name='Город отправления'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_arrivals', to='transport.city', verbose_name='Город назначения'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipmentstatushistory',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transport.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentstatushistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial', to='transport.shipment', verbose_name='Отправка'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='transport.vehicle', verbose_name='Транспорт'),
        ),
    ]
