# Generated by Django 6.0.6 on 2026-06-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для доставки')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cargo_description',
            field=models.TextField(blank=True, verbose_name='Описание груза'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_address',
            field=models.TextField(blank=True, verbose_name='Адрес забора'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_departures', to='transport.city', verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='cargorequest',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_arrivals', to='transport.city', verbose_name='Город назначения'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_departures', to='transport.city', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_arrivals', to='transport.city', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_departures', to='transport.city', verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_arrivals', to='transport.city', verbose_name='Город назначения'),
        ),
    ]
